musicSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notesync.urls')),
    path('user_auth', include('user_auth.urls'))
]

notesync/urls.py
from django.urls import path
from . import views


app_name = 'notesync'
urlpatterns = [
    path('', views.band_list, name='band_list'),
    path('tour_dates/', views.tour_dates, name='tour_dates'),
    path('contact/', views.contact, name='contact'),
]

user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'
urlpatterns = [
     path('', views.user_login, name='login'),
     path('authenticate_user/', views.authenticate_user,
          name='authenticate_user'),
     path('user_registration/', views.user_registration,
          name='user_registration'),
]

notesync/models.py
from django.db import models

# Create your models here.


class Band(models.Model):
    """
    Model representing a band of music:

    Attributes:
        name (str): The name of the band.
        genre (str): The type of music the band plays.
    """
    name = models.CharField(max_length=150)
    genre = models.CharField(max_length=50)


class Song(models.Model):
    """
    Model representing a class.

    Attributes:
        title (str): The name of the song.
        band (Band): The band that performed the song.
                     Linked as a foreign key.
    """
    title = models.CharField(max_length=150)
    band = models.ForeignKey(Band, on_delete=models.CASCADE)

user_auth/models.py
from django.db import models

# Create your models here.

notesync/views.py
from django.shortcuts import render
from .models import Band

# Create your views here.


# Function to render a page with names of different bands.
def band_list(request):
    '''Home page'''
    bands = Band.objects.all()
    return render(request, 'music/band_list.html', {'bands': bands})


def tour_dates(request):
    '''Tour dates page to show vacancy of tickets'''
    return render(request, 'music/tour_dates.html')


def contact(request):
    '''Conact page to show form for fan mail.'''
    return render(request, 'music/contact.html')

user_auth/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
# Function to handle User logins.
def user_login(request):
    '''
    Render the login page
    
    Args:
        request (HttpRequest): The HTTP request object.
        
    Returns:
        HttpResponse: The rendered login page.
    '''
    return render(request, 'authentication/login.html')


# Function to authenticate a user.
def authenticate_user(request):
    '''
    Authenticate a user based on provided username and password.
    
    Args:
        request (HttpRequest): The HTTP request object.
    
    Returns:
        HttpResponse: Redirects to the login page if authentication fails,
                      otherwise, redirects to a page for authenticated users.
    '''
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)

    # If user does not exist, return user back to login page,
    # if user does exist, return user to a new html file.
    if user is None:
        return HttpResponseRedirect(
            reverse('user_auth:login')
        )
    else:
        login(request, user)
        return HttpResponseRedirect(
            reverse('notesync:tour_dates')
        )


# Function to display a register form for new users.
def user_registration(request):
    '''
    Display a registration form for new users
    
    Args:
        request (HttpRequest): The HTTP request object.
    
    Returns:
        HttpReponse: Render the registration form or redirects to a page for
                     authenticated users.
    '''

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect(
                reverse('notesync:tour_dates')
                )
    else:
        form = UserCreationForm

    return render(request, 'authentication/registration.html', {'form': form})

notesync/templates/music/band_list.html
{% load static %}    <!--Load css static files-->


<!-- REFERENCE: W3schools-Bootstrap templates-->
<!--Page to view lists of Bands.-->
<!DOCTYPE html>       
<html lang="eng">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>band_list</title>

        <!--Load Bootstrap-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

        <!--Load style.css-->
        <link rel="stylesheet" href="{%static 'notesync/style.css'%}">

        <!--Load Boostrap JS and jQuery-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>

    <body>

      <!--Nav bar at the top of the home page.-->
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Lumnious Alchemy</a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#band">BAND</a></li>
              <li><a href="{%url 'notesync:tour_dates'%}">TOUR DATES</a></li>
              <li><a href="{%url 'notesync:contact'%}">CONTACT</a></li>
              <li><a href="{%url 'user_auth:login'%}">Sign in</a></li>
              <li><a href="#"><span class="glyphicon glyphicon-search"></span></a></li>
            </ul>
          </div>
        </div>
      </nav>

        
        <div class="container text-center">
            <h2>Lumnious Alchemy</h2>
            <p><em>Music is our passion.</em></p>
            <br><br>

            <h4 id="#band">Meet the Band:</h4>
            <br><br>

            <div class="row">
                <div class="col-sm-6">
                    <p class="text-center"><strong>Zack</strong></p><br>
                    <a href="#demo" data-toggle="collapse">
                    <img src="{% static 'notesync/rudy.jpg' %}" class="img-circle person" alt="zack_band_member">
                    </a>
                    <div id="demo" class="collapse">
                        <p>Guitarist and Lead Vocalist</p>
                        <p>Loves Family</p>
                        <p>EST.2023</p>
                    </div>
                </div>

                <div class="col-sm-6">
                    <p class="text-center"><strong>Shakes</strong></p><br>
                    <a href="#demo2" data-toggle="collapse">
                    <img src="{% static 'notesync/zack.jpg'%}" class="img-circle person" alt="shakes_band_member">
                    </a>
                    <div id="demo2" class="collapse">
                        <p>Drummer</p>
                        <p>Loves Swimming and Jamming</p>
                        <p>EST.2023</p>
                    </div>
                </div>
        </div>
        <br><br>

        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
          
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
              <div class="item active">
                <img src="{% static 'notesync/concert.jpg' %}" width="100%" alt="concert.jpg">
              </div>
          
              <div class="item">
                <img src="{% static 'notesync/drums.jpg' %}" width="100%" alt="drums.jpg">
              </div>
          
              <div class="item">
                <img src="{% static 'notesync/guitar.jpg' %}" width="100%" alt="guitar.jpg">
                <div class="carousel-caption">
              </div>
            </div>
          
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
        </div>
        <br><br>

    </body>

</html>

notesync/templates/music/contact.html
<!--Load Bootstrap-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!--Form from fans to send fan mail.-->
<div class="container">
    <h3 class="text-center">Contact</h3>
    <p class="text-center"><em>We love our fans!</em></p>
    <div class="row test">
      <div class="col-md-4">
        <p>Fan? Drop a note.</p>
        <p><span class="glyphicon glyphicon-map-marker"></span>Cape Town, South Africa</p>
        <p><span class="glyphicon glyphicon-phone"></span>Phone: +27 74 702 5998</p>
        <p><span class="glyphicon glyphicon-envelope"></span>Email: mail@gmail.com</p>
      </div>
      <div class="col-md-8">
        <div class="row">
          <div class="col-sm-6 form-group">
            <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
          </div>
          <div class="col-sm-6 form-group">
            <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
          </div>
        </div>
        <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea>
        <div class="row">
          <div class="col-md-12 form-group">
            <button class="btn pull-right" type="submit">Send</button>
          </div>
        </div>
      </div>
    </div>
  </div>

notesync/templates/music/tour_dates.html
<!--Page to show vacancy of tour dates-->

<!--Load Bootstrap-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!--CSS-->
<style>
    .bg-1 {
    background: #2d2d30;
    color: #bdbdbd;
    }
    .bg-1 h3 {color: #fff;}
    .bg-1 p {font-style: italic;}
    </style>

<!--Show information regarding vacancy tickets for a certain month/date-->
<div class="bg-1">
  <div class="container">
    <h3 class="text-center">TOUR DATES</h3>
    <p class="text-center">We bring illuminating music to you.
        <br> Remember to book your tickets!</p>

    <ul class="list-group">
      <li class="list-group-item">September <span class="label label-danger">Sold Out!</span></li>
      <li class="list-group-item">October <span class="label label-danger">Sold Out!</span></li>
      <li class="list-group-item">November 19</li>
    </ul>
  </div>
</div>

user_auth/templates/authentication/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
        <!--Load Bootstrap-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

        <!--Load Boostrap JS and jQuery-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>

        <body>
        <!--Nav bar at the top of the login page.-->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Lumnious Alchemy</a>
              </div>
              <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'notesync:band_list' %}">HOME</a></li>
                  <li><a href="{% url 'user_auth:user_registration' %}">REGISTER HERE</a></li>
                </ul>
              </div>
            </div>
          </nav>
          <br><br><br>
          
          <h1 style="text-align: center;"> Login as user</h1>

          <form class="container text-center" action="{% url 'user_auth:authenticate_user' %}" method="post">
              {% csrf_token %}
        
              <label>Username</label>
              <input type="text" name="username" placeholder="User" required>
              <br/><br/>
        
              <label>Password</label>
              <input type="password" name="password" required>
              <br/><br/>
        
              <input type="submit" value="login" />

          </form>        
    </body>
</html>

user_auth/templates/authentication/registration.html
<!DOCTYPE html>

<html>
    <head>
        <title>Register</title>
        <!--Load Bootstrap-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

        <!--Load Boostrap JS and jQuery-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>

    <body>
        <!--Nav bar at the top of the login page.-->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Lumnious Alchemy</a>
              </div>
              <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'notesync:band_list' %}">HOME</a></li>
                </ul>
              </div>
            </div>
        </nav>

        <br><br><br>
        <h1 style="text-align: center;">User Reigstration</h1>
            
        <form class="container text-center" method="post" action="{% url 'user_auth:user_registration' %}">
            {% csrf_token %}
            <!--Space form out-->
            {{form.as_p}}
            <br/><br/>
        
            <button class="btn btn-primary" type="submit">Register</button>
        </form>
    </body>
</html>